<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net461;net45;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <AssemblyTitle>进程守护</AssemblyTitle>
    <Description>持续监控你的应用，如果应用崩溃、卡顿或停止，会自动重启。它非常适合让非服务应用在后台运行，并确保它们在系统启动时自动启动，甚至在登录前就启动，无需重写为服务。QQ:2492123056</Description>
    <Company>科控物联</Company>
    <Copyright>©2002-2026 TC</Copyright>
    <VersionPrefix>3.7</VersionPrefix>
    <VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
    <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(VersionPrefix).*</AssemblyVersion>
    <Deterministic>false</Deterministic>
    <OutputPath>..\Bin\Agent</OutputPath>
    <!--<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>-->
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\favicon.ico</ApplicationIcon>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\Doc\newlife.snk</AssemblyOriginatorKeyFile>
    <IsPackable>False</IsPackable>
    <NoWarn>1701;1702;NU5104;NETSDK1138;CS7035;CS8600;CS8602;CS8603;CS8604;CS8618;CS8619;CS8622;CS8625</NoWarn>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net8.0'">
    <!--<ServerGarbageCollection>true</ServerGarbageCollection>-->
    <!--<GarbageCollectionAdaptationMode>1</GarbageCollectionAdaptationMode>-->
    <!--<PublishAot>true</PublishAot>-->
    <!--<OptimizationPreference>Size</OptimizationPreference>-->
    <!--<InvariantGlobalization>true</InvariantGlobalization>-->
    <!--<StackTraceSupport>false</StackTraceSupport>-->
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Stardust\Managers\FirewallManager.cs" Link="Managers\FirewallManager.cs" />
    <Compile Include="..\Stardust\Managers\ServiceController.cs" Link="Managers\ServiceController.cs" />
    <Compile Include="..\Stardust\Managers\ServiceManager.cs" Link="Managers\ServiceManager.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ILRepack" Version="2.0.44" Condition="'$(TargetFramework)'=='net461'">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <EmbeddedResource Include="WebPanel\wwwroot\**" />
    <PackageReference Include="NewLife.Agent" Version="10.17.2026.801" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stardust\Stardust.csproj" />
  </ItemGroup>

  <Import Project="ILRepack.targets" Condition="'$(TargetFramework)'=='net461'" />

</Project>
